language: node_js
node_js:
  - "node"
  - "lts/*"
dist: xenial
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
